// Generated by CoffeeScript 1.6.3
Handlebars.registerHelper("key_value", function(context, options) {
  var result;
  result = [];
  _.each(context, function(value, key, list) {
    return result.push({
      key: key,
      value: value
    });
  });
  return result;
});
